date = '231103'
target_dir = f'./datasets/{date}'
dataset = "TIN-no-resize2"
LOG_FILE_NAME = "taken_log_env_control_auto_TIN-no-resize2_1103.pickle"
PARAM_TOTAL_NUM = 5
VALID_LENGTH = -1 #if every data is valid (no memory fulled issue)
OPTION = 'auto'
delayed = []
blanks = []
